# Generated by Django 4.2.1 on 2023-05-30 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productosapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
        migrations.AlterField(
            model_name='producto',
            name='category',
            field=models.CharField(choices=[('Acc', 'Accion'), ('Adv', 'Aventura'), ('Arc', 'Arcade'), ('Dep', 'Deportes'), ('Est', 'Estrategia'), ('Sim', 'Simulacion'), ('Gad', 'Aventura Grafica'), ('Rol', 'Rol'), ('Mus', 'Musical'), ('Box', 'Sandbox'), ('Ter', 'Terror')], max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='description',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='producto',
            name='img',
            field=models.ImageField(upload_to='productosapp'),
        ),
    ]
