# Generated by Django 4.2.1 on 2023-06-06 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productosapp', '0002_alter_producto_options_alter_producto_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='prolink',
            field=models.URLField(default='https://www.epicgames.com/site/es-ES/home?sessionInvalidated=true'),
        ),
    ]
