# Generated by Django 4.2.1 on 2023-06-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0002_publicaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='image',
            field=models.ImageField(default='foto_perfil/1600w-41B81rUGLAg.webp', upload_to='productosapp'),
        ),
    ]
